# Generated by Django 3.0.4 on 2020-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200330_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='setname',
            field=models.TextField(default='-'),
        ),
    ]
